---
- name: Playbook to Download and Deploy Artifact in tomcat
  hosts: "{{ deploy_host }}"    
  tasks:
  - name: Create tomcat9 group
      ansible.builtin.group:
        name: tomcat9
        state: present

  - name: Create tomcat9 user
      ansible.builtin.user:
        name: tomcat9
        group: tomcat9
        home: /opt/tomcat
        shell: /bin/false
        state: present

  - name: Set ownership of tomcat directory
      ansible.builtin.file:
        path: /path/to/tomcat
        state: directory
        owner: tomcat9
        group: tomcat9
        mode: '0755'
  
  - name: Create a Directory /opt/Downloads
    become: yes
    file:
      path: /opt/Downloads
      state: directory
      mode: 0755
      owner: tomcat9
      group: tomcat9

  - name: Download Artifact from Artifactory
    become: yes
    get_url:
      url: http://3.140.250.238:8082/artifactory/jackpiro-snapshot-repo-local/com/mkyong/JackPiro/1.2.17-SNAPSHOT/JackPiro-1.2.17-20250107.080042-1.war
      url_password: Admin123
      url_username: admin
      dest: /opt/Downloads/JackPiro.war
      mode: 0755
      group: tomcat9
      owner: tomcat9
      
  - name: Copy File to webapp folder
    become: yes
    copy:
      src: /opt/Downloads/JackPiro.war
      dest: /var/lib/tomcat9/webapps
      remote_src: yes
      mode: 0755
      owner: tomcat9
      group: tomcat9
      
  - name: Delete a Directory /opt/Downloads
    become: yes
    file:
      path: /opt/Downloads
      state: absent
