---
- name: Deploy artifact to Tomcat server
  hosts: "{{ deploy_host }}"
  become: true
  vars:
    download_path: /home/{{ ansible_user }}/Downloads
    artifact_url: http://3.138.197.249:8082/artifactory/jackpiro-snapshot-repo-local/com/mkyong/JackPiro/1.2.12-SNAPSHOT/JackPiro-1.2.12-20250107.062734-1.war
    tomcat_webapps_path: /var/lib/tomcat9/webapps
  tasks:

    - name: Ensure Downloads directory exists
      ansible.builtin.file:
        path: "{{ download_path }}"
        state: directory
        mode: '0755'

    - name: Download artifact from JFrog Artifactory
      ansible.builtin.get_url:
        url: "{{ artifact_url }}"
        url_password: Admin123
        url_username: admin
        dest: "{{ download_path }}/JackPiro.war"
        mode: '0644'

    - name: Copy artifact to Tomcat webapps directory
      ansible.builtin.copy:
        src: "{{ download_path }}/JackPiro.war"
        dest: "{{ tomcat_webapps_path }}/JackPiro.war"
        remote_src: yes

    - name: Ensure proper permissions for the artifact in webapps
      ansible.builtin.file:
        path: "{{ tomcat_webapps_path }}/JackPiro.war"
        owner: tomcat9
        group: tomcat9
        mode: '0644'

    - name: Restart Tomcat service
      ansible.builtin.service:
        name: tomcat9
        state: restarted

    - name: Remove Downloads directory
      ansible.builtin.file:
        path: "{{ download_path }}"
        state: absent
